---

# It is less problematic to do it this way
# than using the repository
#
- name: NodeJS Repository (RedHat)
  shell: >
    curl --silent --location {{nodejs_setup_url}} | sudo bash -

- name: Install NodeJS (RedHat)
  yum:
    state=present
    update_cache=yes
    name="nodejs"

# vi:ts=2:sw=2:et:ft=yaml
